---
- id: snyk-container
  name: Snyk Container
  description: Runs 'snyk container test' command
  entry: hooks/snyk-container.sh
  language: script
  pass_filenames: true
  files: Dockerfile
  types: [file, text]

- id: snyk-iac
  name: Snyk IaC
  description: Runs 'snyk iac test' command
  entry: hooks/snyk-iac.sh
  language: script
  pass_filenames: false
  verbose: true

- id: snyk-test
  name: Snyk Test
  description: Runs 'snyk test' command
  entry: hooks/snyk-test.sh
  language: script
  pass_filenames: false
  verbose: true

- id: snyk-code
  name: Snyk Code
  description: Runs 'snyk code test' command
  entry: hooks/snyk-code.sh
  language: script
  pass_filenames: false
  verbose: true

- id: snyk-log4shell
  name: Snyk log4shell
  description: Runs 'snyk log4shell' command
  entry: hooks/snyk-log4shell.sh
  language: script
  pass_filenames: false
  pass_filenames: false
  verbose: true