repos:
  - repo: local
    hooks:
      - id: pre-commit-autoupdate
        name: pre-commit-autoupdate
        entry: pre-commit autoupdate
        language: system
        pass_filenames: false
        verbose: true
  # Security
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.1.2
    hooks:
      - id: gitleaks
  # Markdown
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: 0.9.2
    hooks:
      - id: pymarkdown
  # Shell
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.1
    hooks:
      - id: shellcheck
  # Other
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
      - id: trailing-whitespace
